name = "AudioPlugins"
uuid = "83119930-5344-4127-8689-15f5870d6d1a"
authors = ["JuliaHub, Inc. and contributors"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
